spring.application.name: platform-engineering
profile-specific-property: default
management:
  endpoints:
    web:
      exposure:
        include: flywayMigrate
  endpoint:
    flywayMigrate:
      enabled: true